language: php

php:
  - 8.1
  - 8.2
  - 8.3
  - hhvm

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - composer self-update
  - composer install --dev --prefer-source

script:
  - composer check

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
  - CODECLIMATE_REPO_TOKEN=573d86e6238ed49e0ec0628addea7fb3ac46d9649b6b3a32a994a81eaf05d2e6 ./vendor/bin/test-reporter --coverage-report=coverage.clover

notifications:
  email: true
